// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP5xyxwF3ZtRuG0dpLZ_kFoC98LNm0Zgw',
    appId: '1:452018113766:web:f7b202aba7d3f924f1bf27',
    messagingSenderId: '452018113766',
    projectId: 'chatapp-40b91',
    authDomain: 'chatapp-40b91.firebaseapp.com',
    storageBucket: 'chatapp-40b91.firebasestorage.app',
    measurementId: 'G-9KSHK60GZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqr0SK76AYjKnul-MjeJf9UhEZL02UxV4',
    appId: '1:452018113766:android:6a19da93077d1a67f1bf27',
    messagingSenderId: '452018113766',
    projectId: 'chatapp-40b91',
    storageBucket: 'chatapp-40b91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpyGrFTZzjAIIQyyZd_2S4IaW3I0aQkhg',
    appId: '1:452018113766:ios:fa976a572d5b0e3af1bf27',
    messagingSenderId: '452018113766',
    projectId: 'chatapp-40b91',
    storageBucket: 'chatapp-40b91.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpyGrFTZzjAIIQyyZd_2S4IaW3I0aQkhg',
    appId: '1:452018113766:ios:fa976a572d5b0e3af1bf27',
    messagingSenderId: '452018113766',
    projectId: 'chatapp-40b91',
    storageBucket: 'chatapp-40b91.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP5xyxwF3ZtRuG0dpLZ_kFoC98LNm0Zgw',
    appId: '1:452018113766:web:0bf8905aa94c00dcf1bf27',
    messagingSenderId: '452018113766',
    projectId: 'chatapp-40b91',
    authDomain: 'chatapp-40b91.firebaseapp.com',
    storageBucket: 'chatapp-40b91.firebasestorage.app',
    measurementId: 'G-V5259D7K7X',
  );
}
